modLoader="javafml"
loaderVersion="${neo_loader_version_range}"
issueTrackerURL="${issueTrackerURL}"
license="${mod_license}"
[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${display_name}"
    displayURL="${displayURL}"
    authors="${mod_authors}"
    description="${mod_description}"
    logoFile="icon.png"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${neo_minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[modproperties.${mod_id}]
    catalogueItemIcon="${catalogueItemIcon}"